source 'https://github.com/CocoaPods/Specs.git'

platform :ios, '9.0'

inhibit_all_warnings!

target 'LYResourceKit_Example' do
	use_frameworks!
	pod 'LYResourceKit', :path => '../'

	target 'LYResourceKit_Tests' do
		inherit! :search_paths
	end
end
